### ISSUE TITLE
Use embed code in Portfolio Archive section

### ISSUE THREAD

**Issue by theVasilis** [studiopress/genesis-portfolio-pro#21]
I’m trying to embed a YouTube video in the Portfolio Type archive section.

Tried with iframe code, WordPress embed code and just using a plain link but nothing works.

The Portfolio Archive just shows the code…

Is there a way we can make the Portfolio Archive read the embed code and bring up the video?

**Comment by nickcernis** [comment]
This relates to how Genesis outputs archive intro text. (It runs text through wpautop but no other functions.)

You could use this code in your theme's `functions.php` to process shortcodes and oembeds too:
~~~php
add_action( 'genesis_meta', 'custom_filter_archives' );
function custom_filter_archives() {
	global $wp_embed;
	add_filter( 'genesis_term_intro_text_output', array( $wp_embed, 'autoembed' ) );
	add_filter( 'genesis_term_intro_text_output', 'do_shortcode' );
}
~~~

**Comment by nickcernis** [comment]
@theVasilis The code has not been included as part of the plugin, as it relates to a Genesis feature rather than a plugin feature.

I have opened an issue in the main Genesis repository to see if there is interest in adding it to Genesis.

The code above is still safe to add to sites for now. If Genesis includes it in the future it will not break your site.
